ChromeOsStr: linux
BuildDepsOpts:
- '--no-arm'
- '--no-chromeos-fonts'
- '--no-nacl'
GnOpts:
- 'enable_libaom=false'
- 'libyuv_disable_jpeg=true'
- 'rtc_build_opus=false'
- 'rtc_enable_protobuf=false'
- 'rtc_include_builtin_audio_codecs=false'
- 'rtc_include_builtin_video_codecs=false'
- 'rtc_include_builtin_video_codecs=false'
- 'rtc_include_ilbc=false'
- 'rtc_include_internal_audio_device=false'
- 'rtc_include_opus=false'
- 'rtc_include_pulse_audio=false'
- 'rtc_use_dummy_audio_file_devices=true'
- 'rtc_use_x11=false'
- 'target_cpu="x64"'
- 'target_os="linux"'
- 'use_custom_libcxx=false'
- 'use_libjpeg_turbo=false'
- 'use_rtti=true'
- 'use_system_libjpeg=true'
BuildTargets:
- 'peerconnection_client'
NinjaFile: obj/examples/peerconnection_client.ninja
NinjaTarget: 'peerconnection_client:'
ExcludeFiles:
- 'obj/examples'
- 'obj/test'
Headers:
# see https://webrtc.googlesource.com/src/+/master/native-api.md for maintenance
- 'common_audio/include'
- 'media/base'
- 'media/engine'
- 'modules/audio_coding/include'
- 'modules/audio_device/include'
- 'modules/audio_processing/include'
- 'modules/congestion_controller/include'
- 'modules/include'
- 'modules/rtp_rtcp/include'
- 'modules/rtp_rtcp/source'
- 'modules/utility/include'
- 'modules/video_coding/codecs/h264/include'
- 'modules/video_coding/codecs/vp8/include'
- 'modules/video_coding/codecs/vp9/include'
- 'modules/video_coding/include'
- 'pc'
- 'system_wrappers/include'
# add by myself
- 'call'
- 'common_video'
- 'common_video/include'
- 'common_video/generic_frame_descriptor'
- 'logging/rtc_event_log'
- 'logging/rtc_event_log/events'
- 'logging/rtc_event_log/encoder'
- 'modules/async_audio_processing'
- 'modules/rtp_rtcp/source/rtcp_packet'
- 'modules/video_coding'
- 'modules/video_coding/codecs/interface'
- 'p2p/base'
- 'video/config'
HeadersWithSubdir:
- 'api'
# add by myself
- 'rtc_base'
- 'third_party/abseil-cpp/absl'
