ChromeOsStr: mac
GnOpts:
- 'is_component_build=false'
- 'rtc_build_opus=false'
- 'rtc_enable_protobuf=false'
- 'rtc_include_builtin_audio_codecs=false'
- 'rtc_include_builtin_video_codecs=false'
- 'rtc_include_builtin_video_codecs=false'
- 'rtc_include_ilbc=false'
- 'rtc_include_internal_audio_device=false'
- 'rtc_include_opus=false'
- 'rtc_include_pulse_audio=false'
- 'rtc_use_dummy_audio_file_devices=true'
- 'rtc_use_gtk=false'
- 'rtc_use_x11=false'
- 'target_cpu="x64"'
- 'target_os="mac"'
- 'use_custom_libcxx=false'
- 'use_rtti=true'
BuildTargets:
- 'obj/sdk/mac_framework_objc_shared_library/WebRTC'
NinjaFile: obj/sdk/mac_framework_objc_shared_library.ninja
NinjaTarget: 'obj/sdk/mac_framework_objc_shared_library/WebRTC.TOC:'
ExcludeFiles:
- 'obj/examples'
- 'obj/test'
Headers:
# see https://webrtc.googlesource.com/src/+/master/native-api.md for maintenance
- 'common_audio/include'
- 'media/base'
- 'media/engine'
- 'modules/audio_coding/include'
- 'modules/audio_device/include'
- 'modules/audio_processing/include'
# - 'modules/bitrate_controller/include'
- 'modules/congestion_controller/include'
- 'modules/include'
- 'modules/remote_bitrate_estimator/include'
- 'modules/rtp_rtcp/include'
- 'modules/rtp_rtcp/source'
- 'modules/utility/include'
- 'modules/video_coding/codecs/h264/include'
- 'modules/video_coding/codecs/vp8/include'
- 'modules/video_coding/codecs/vp9/include'
- 'modules/video_coding/include'
- 'pc'
# - 'rtc_base'
- 'system_wrappers/include'
# add by myself
- '.'
- 'call'
- 'common_video'
- 'common_video/include'
- 'common_video/generic_frame_descriptor'
- 'logging/rtc_event_log'
- 'logging/rtc_event_log/events'
- 'modules/async_audio_processing'
- 'modules/rtp_rtcp/source/rtcp_packet'
- 'modules/video_coding'
- 'modules/video_coding/codecs/interface'
- 'p2p/base'
HeadersWithSubdir:
- 'api'
# add by myself
- 'rtc_base'
- 'third_party/abseil-cpp/absl'
